package ui;

public enum ControllerState {
	sMAIN, sLOGIN, sSELECTPROJECT, sPROJECT, sVIEWDEVS, sMANAGEPROJECT, sSELECTACTIVITY, sACTIVITY, 
	sREGISTERTIME, sEDITREGISTEREDTIME, sASSISTANCE, sVIEWTIME, sREMOVEASSTDEV, sCHANGEBUDGETHOURS,
	sADDDEVPROJ, sREMOVEDEVPROJ, sCHANGEPROJMAN, sGETTIMEREPORT, sADDDEVACT, sREMOVEDEVACT,
	sCHANGESTARTWEEK, sCHANGESTOPWEEK;
}

