package ui;

public enum ControllerStateEnum {
	sMAIN, sLOGIN, sSELECTPROJECT, sPROJECT, sVIEWDEVS, sNEWPROJECT, sMANAGEPROJECT, sSELECTACTIVITY, sACTIVITY, 
	sREGISTERTIME, sEDITREGISTEREDTIME, sASSISTANCE, sVIEWTIME, sREMOVEASSTDEV, sCHANGEBUDGETHOURS,
	sADDDEVPROJ, sREMOVEDEVPROJ, sCHANGEPROJMAN, sGETTIMEREPORT, sADDDEVACT, sREMOVEDEVACT,
	sCHANGESTARTWEEK, sCHANGESTOPWEEK, sNEWACTIVITY;
}

