package ui;

/**
 * 
 * @author Kasper Hesse, s183735
 *
 */
public enum ControllerState {
	sMAIN, sLOGIN, sSELECTPROJECT, sPROJECT, sVIEWDEVS, sNEWPROJECT, sMANAGEPROJECT, sSELECTACTIVITY, sACTIVITY, 
	sREGISTERTIME, sEDITREGISTEREDTIME, sASSISTANCE, sVIEWTIME, sREMOVEASSTDEV, sCHANGEBUDGETHOURS,
	sADDDEVPROJ, sREMOVEDEVPROJ, sCHANGEPROJMAN, sGETTIMEREPORT, sADDDEVACT, sREMOVEDEVACT,
	sCHANGESTARTWEEK, sCHANGESTOPWEEK, sNEWACTIVITY;
}

