package ui;

import java.util.List;
import java.util.stream.Collectors;

import dto.DTOinterface;
import schedulingapp.*;

/**
 * 
 * @author Kasper Hesse, s183735
 *
 */
public class SchedulingAppCLI {
	
	public SchedulingAppCLI() {
		
	}
	
	/**
	 * Shows an error message generated by the controller. Should *not* be used for error messages taken from exceptions
	 * @param errorMsg
	 */
	void showError(String errorMsg) {
		String[] tokens = errorMsg.split("\n");
		System.out.printf("ERROR:\t%s\n", tokens[0]);
		for(int i = 1; i<tokens.length; i++) {
			System.out.printf("\t%s\n", tokens[i]);
		}
	}

	/**
	 * Shows an information message to the user of the application
	 * @param message The message to show
	 */
	public void showMessage(String message) {
		String[] tokens = message.split("\n");
		System.out.printf("INFO:\t%s\n", tokens[0]);
		for(int i = 1; i<tokens.length; i++) {
			System.out.printf("\t%s\n", tokens[i]);
		}
	}

	/**
	 * Shows a list of options to the user of the application. 
	 * @param options The options to be shown
	 */
	public void showOptions(String[] options) {
		showOptions(options, "Please select one of the below options:");
//		System.out.println("Please select one of the below options: ");
//		for(int i=0; i<options.length; i++) {
//			System.out.printf("[%d] %s\n", i, options[i]);
//		}
	}
	
	/**
	 * Shows a list of options to the user of the application
	 * @param options The options to be shown
	 * @param showHeader An optional header to be shown before the options
	 */
	public void showOptions(String[] options, String header) {
		if(!header.equals("")) {
			System.out.println(header);
		}
		for(int i=0; i<options.length; i++) {
			System.out.printf("[%d] %s\n", i, options[i]);
		}
	}

	/**
	 * Shows a list of options to the user of the application
	 * @param options A list of objects that implement DTOinterface
	 */
	public void showOptions(List<? extends DTOinterface> options) {
		showOptions(options, "Please select one of the below options");
	}
	
	public void showOptions(List<? extends DTOinterface> options, String header) {
		List<String> strings = options.stream().map(o -> o.toPrint()).collect(Collectors.toList());
		showOptions(strings.toArray(new String[0]), header);
	}
	
	
}
